Repository BirnadinErick/spc-175, pull requests merged in 2023-11, with the labels that each got.

#27 first commit add academics sections #18
  src/pages/academics/index.html
Labels: good first issue, wontfix

#30 Academics Page (mobile MVP)
  src/assets/how_join_school.png
  src/components/academics/Flattered.astro
  src/components/academics/MoreNews.astro
  src/components/academics/SoFar.astro
  src/components/academics/SoFarCard.astro
  src/components/footer/FooterTail.astro
  src/components/home/AboutText.astro
  src/components/home/Hero.astro
  src/components/home/PatricianNorms.astro
  src/components/home/PatricianToday.astro
  src/layouts/PostLayout.astro
  src/pages/academics/index.astro
  src/pages/academics/index.html
  src/pages/index.astro
  src/pages/patrician-publications/index.astro
  tsconfig.json
Labels: enhancement

#45 Add Sports page
  src/components/sports/Team.astro
  src/components/sports/TeamGroup.astro
  src/components/sports/Teams.astro
  src/pages/sports/index.astro
Labels: enhancement

#47 Change Footer
  src/components/footer/FooterAcknowledgement.astro
Labels: bug

#55 Reduce post card x padding
  src/components/patrician-publications/Feature.astro
  src/components/patrician-publications/PatricianPublicationCard.astro
  src/pages/patrician-publications/index.astro
Labels: bug

#64 Fix inconsistent padding closes #57
  src/pages/our-spirituality/index.astro
Labels: bug
